### ISSUE TITLE
Windows bug with file uploading

### ISSUE THREAD

**Issue by filefilegoadmin** [filefilego/filefilego#111]
**Describe the bug**
When a file is being uploaded, there is a bug in windows

failed to move uploaded file: rename C:\\Users\\ffg\\Downloads\\storage/2023-04-18/0x1b3577852f49be16041952fc088687c937a348fc74b869c101119bbf89abc102da63f3256960ebb6 C:\\Users\\ffg\\Downloads\\storage/2023-04-18/e9f42a242416c6f91d45b0464ff24ea8f617e26d: The process cannot access the file because it is being used by another process."

**To Reproduce**
Just setup a storage node and upload content

**Expected behavior**
Shouldn't fail

**Comment by filefilegoadmin** [comment]
I believe the error is from because we use `path.Join` and not `filepath.Join`

**Comment by connector** [comment]
Yes this could be the case, on linux i tried to see the file paths and they were fine

**Comment by filefilegoadmin** [comment]
Creating a pr to solve it

**Comment by connector** [comment]
According to go's doc, `filepath` is OS aware so this should do the work

**Comment by filefilegoadmin** [comment]
Done
