### ISSUE TITLE
Add discovered peer's block height to filefilego.Stats

### ISSUE THREAD

**Issue by connector** [filefilego/filefilego#130]
We should add the highest block available within the network that was discovered by the discovery protocols to the Stats rpc method. In this we way we know if a node is behind the highest chain. For instance a storage node could be out of sync and this would be an indicator

**Comment by filefilegoadmin** [comment]
Good idea! currently we can see the local blockchain height in the `stats` rpc method. Feel free to open a pr

**Comment by filefilegoadmin** [comment]
I will work on this one

**Comment by filefilegoadmin** [comment]
Done
