### ISSUE TITLE
Purge data query requests from the store after 5 mins

### ISSUE THREAD

**Issue by filefilegoadmin** [filefilego/filefilego#142]
We should purge data query requests from the store after 5 mins. The average time window for a user to see if their request was satisfied within the network is 10 seconds

**Comment by vijayraghav-io** [comment]
Hi @filefilegoadmin , I am interested to work on this. Please assign.

**Comment by filefilegoadmin** [comment]
hi @vijayraghav-io Sure, feel free to open a PR and I will guide if you need any help
