### ISSUE TITLE
Add uptime for storage providers

### ISSUE THREAD

**Issue by filefilegoadmin** [filefilego/filefilego#183]
When there is a search request for storage providers, the list includes the country of each provider, there is a button to test the throughput of each provider.

Now we would like to also show the uptime of the provider, that is the uptime of the filefilego application. We could also include the uptime of the system which might be useful in the future. For instance, helping with choosing a better storage provider by monitoring its uptime and other stats.

However it's well known that a client must not be trusted with those values as they can easily be changed

**Comment by filefilegoadmin** [comment]
We also want to know the storage capacity of the node, which can be done by getting the size of storage_folder.

This metadata should be added to the response of a storage query request

**Comment by filefilegoadmin** [comment]
> 

The system call for this is implemented in https://github.com/filefilego/filefilego/pull/187

**Comment by connector** [comment]
Done
