### ISSUE TITLE
Fix data query purging

### ISSUE THREAD

**Issue by filefilegoadmin** [filefilego/filefilego#184]
The data query purging depends on the timestamp within the envelope. A node with out of sync timestampstamp will behave abnormally. When a request is stored inmem, make sure to keep a local timestamp

**Comment by vijayraghav-io** [comment]
@filefilegoadmin  can you assign this to me

**Comment by filefilegoadmin** [comment]
Sure, let me know if you have any questions :)

**Comment by filefilegoadmin** [comment]
This is also a priority for the UI release, please let me know about the progress @vijayraghav-io if you are stuck somewhere so i help

**Comment by vijayraghav-io** [comment]
> This is also a priority for the UI release, please let me know about the progress @vijayraghav-io if you are stuck somewhere so i help

Yes @filefilegoadmin i am on it, will let you know if any more details required.
Will try to close this by today.

**Comment by filefilegoadmin** [comment]
Done
