### ISSUE TITLE
[CLI] EVM compatible transaction and addresses

### ISSUE THREAD

**Issue by filefilegoadmin** [filefilego/filefilego#288]
It would be great if we could utilize wallets like metamask to interact with the filefilego blockchain. One way to do this is to implement the evm rpcs and the transaction structure.
This means we need to implement the transaction structure of ethereum, signing and validating transactions and so on.

**Comment by filefilegoadmin** [comment]
Work to do:
1. Address generation which is fully compatible with ETH
2. Transaction-related functionality
3. RPCs
4. Extend the code to support this new method

**Comment by iNDicat0r** [comment]
I merged this PR with main and tested with mainntet, transactions are working properly
