### ISSUE TITLE
create a community forum and chat

### ISSUE THREAD

**Issue by marcoperp** [filefilego/filefilego#306]
Hi team

I am using filefilego for a personal project! so far i am happy about it
my suggestions:
1. create a forum
2. use matrix instead of discord
3. fix docs because some flags are missing
4. you need a service like etherscan

**Comment by filefilegoadmin** [comment]
Hi
1. We currently have discord however a forum would be even better for a community
2. I will investigate
3. You are right, I will create a ticket for this
4. We have a ticket for this, feel free to work in it if you would like :)

**Comment by marcoperp** [comment]
i will create a pr with my changes
