### ISSUE TITLE
Project Still Active?

### ISSUE THREAD

**Issue by lonnietc** [filefilego/filefilego#4]
Hello,

I would like to discuss this project with you more and to also see if it is still active.

Best Regard and looking forward to hearing from you.

**Comment by lonnietc** [comment]
I am able to compile filefilego now and even start it up but there seems to be no documentation on how to add files to a storage node and then accessing those files from other nodes.

Also, there does not seem to be a Go client wallet to access the blockchain and check user account.

Your documentation is pretty good but seems to be missing in some of these aspects which are not clear to me.

Can you please help?
Thanks

**Comment by lonnietc** [comment]
Hello, 

Any updates on this?

**Comment by filefilegoadmin** [comment]
> Hello,
> 
> Any updates on this?

Hi @lonnietc We are working on releasing v2 of filefilego which is a major refactoring. Please keep an eye on here so we will announce

**Comment by lonnietc** [comment]
Hello @filefilegoadmin and Thanks for the update as I had feared that the project was inactive.

That is great news to hear about the v2 effort and I will look forward to seeing when it is available.

Regarding the current v1, I was able to work through everything and got to the last steps in the documentation about setting up a full storage node which is what I am interested in doing.   The docs show how to start the full storage node with a directory space, but does not discuss or show how to add file through the node so that it will be able to serve them to other nodes and users since just placing file in that directory space did not seem reasonable.

Also, I would like to discuss the project that I currently have underway with you offline via email to see if you think that there is a synergy for collaboration and for the incorporation of your FileFileGo into this new project what is expected to go online early next year.  

Please contact me so that we can chat a little bit more on this topic, ok 

```
lonnie@outstep.com
```

I will look forward to hearing from you so that we can discuss it a bit more to see what may, or may not, be possible together.

Thanks and have a great day.

**Comment by lonnietc** [comment]
Well, I guess that I will have to go and search for another storage blockchain like Siacoin, Storj, or Filecoin to work with them for this part of the project since it seems that you are not truly interested in discussing it or working together. 

I had great hopes for the use of FilefileGo but will have to look elsewhere for a viable alternative.
Thanks and have a great day
