### ISSUE TITLE
No retry when sending data to verifier

### ISSUE THREAD

**Issue by connector** [filefilego/filefilego#99]
Hi

In `data_verification.go` inside `handleIncomingFileTransfer(s network.Stream)` the data is sent to verifier without retry mechanism. I think there should be a way to retry in case network fails

**Comment by filefilegoadmin** [comment]
Hey, indeed and there should be a resumable file upload functionality to the verifier same way there is for the file downloader node

**Comment by filefilegoadmin** [comment]
Closing this

Thanks @koschos
